[package]
name = "ico"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "s"

[dependencies]
js-sys = "0.3.61"
wasm-bindgen = "0.2.84"
wee_alloc = "0.4.5"
