name: Deploy to Cloudflare Pages
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: favicon-generator
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
