name: Deploy to Cloudflare Pages
on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: shun-shobon/actions/setup-node@master
        with:
          node-version: lts/*

      - run: pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: favicon-generator
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
